import pygame

CELL = 12
NUM_ROW = 50
NUM_COL = 27
SCREEN_WIDTH = NUM_COL * CELL
SCREEN_HEIGHT = NUM_ROW * CELL

PLASTIC = "plastic"
PAPER = "paper"
GLASS = "glass"

LEFT_KEY = pygame.K_LEFT
RIGHT_KEY = pygame.K_RIGHT

TRASH_BIN_SIZE = (8 * CELL, 8 * CELL)
HEART_SIZE = (3 * CELL, 3 * CELL)
TRASH_SIZE = (5 * CELL, 5 * CELL)

RED = (255, 0, 0)
FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * SCREEN_WIDTH)
LOSE_COLOR = RED
LOSE_LOCATION = \
    (0.2 * SCREEN_WIDTH, SCREEN_HEIGHT/ 2 - (LOSE_FONT_SIZE / 2))

GREEN = (0, 100, 0)
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = GREEN
WIN_LOCATION = \
    (0.2 * SCREEN_WIDTH, SCREEN_HEIGHT / 2 - (WIN_FONT_SIZE / 2))


